### ISSUE TITLE
Multiple space problem

### ISSUE THREAD

**Issue by petersirka** [marexandre/jquery.textarea-highlighter.js#4]
Hi @marexandre,
firstly: your jQuery plugin is very good, thanks for it. I have found a problem: When I add more spaces in a row then the plugin didn't render the highlight very good:

![image](https://cloud.githubusercontent.com/assets/2414252/7043760/8c04852a-ddec-11e4-9e65-46396f68ead1.png)

Many thanks!

**Comment by petersirka** [comment]
I have solved the problem with: `.textarea-highlighter-wrap { white-space:pre; }`
Thanks!

**Comment by marexandre** [comment]
@petersirka Hi, sorry I couldn't reply in time. Glad you could solve it :smile:
Please let me know if you have any other issues.
