### ISSUE TITLE
Match at the beginning of the first line

### ISSUE THREAD

**Issue by selamhabibi** [marexandre/jquery.textarea-highlighter.js#5]
Hi,

thank you for the great work. I've found, if the first word should be marked, the matching does not apply. 
The behavior can also be observed in the demo: (try "for them" at the beginning of the first line)

=>  http://marexandre.com/jquery.textarea-highlighter.js/demo/

Do you have a tip how I can fix it?

Browser:
Firefox 37.0.2 
Chrome Version 42.0.2311.152 m

Thanks

**Comment by marexandre** [comment]
Hi @selamhabibi, will take a look and try to fix it! Thanks for letting me know about this issue :)

**Comment by marexandre** [comment]
Hi @selamhabibi ,

I just pushed 0.6.4 version with a fix to your issue. Could you please use the latest version to to check is it fixed you issue :smile:
