### ISSUE TITLE
RegEx example

### ISSUE THREAD

**Issue by sidorovich** [marexandre/jquery.textarea-highlighter.js#6]
Hi!
I found your plugin on http://www.jqueryscript.net/text/jQuery-Based-Text-Highlighter-For-Textarea.html
In examples using regular expession for matching, but I got error if try to use it. I can't find any information about using regular expressions on your site and examples.

Please, can you help me with examples, or your plugin does not support it yet?
Thx

**Comment by marexandre** [comment]
@sidorovich Hi! I dropped RegEx support when updating the plugin to v0.6.0 as the algorithm changes for finding words to highlight. I will try to make an example or try to add some support for RegEx. Sorry for the confusion, the data on that link seems to be old :/

**Comment by marexandre** [comment]
Hi @sidorovich

I just released `v0.6.6` with add **RegEx** support. I have't tested it with edge cases etc. Could you please try it out and see if it works for your case?

You just have to put some RegEx into the `match` like below
```js
$('#someElement').textareaHighlighter({
    matches: [
        {
            'match': /\{\/?\d+\}/g,
            'matchClass': 'tags'
        }
    ]
});
```

Thanks for trying out my plugin, please let me know if you have any further issues :smile:

**Comment by sidorovich** [comment]
I had problems with RegEx with escaping, like ```/"(?:[^\\]|\\.)*?"/``` or ```/{(?:[^\\]|\\.)*?}/```
We using CodeMirror now instead your plugin. Thx for answer.

**Comment by marexandre** [comment]
@sidorovich Haha, glad you fond some other solution :)
